# Generated by Django 5.0.3 on 2024-03-19 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_customuser_referral_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralcode',
            name='id',
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
