# Generated by Django 5.0.3 on 2024-03-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_referralcode_id_alter_referralcode_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralcode',
            name='reference_code',
        ),
        migrations.AddField(
            model_name='referralcode',
            name='referral_code',
            field=models.CharField(default=1, max_length=20, verbose_name='Реферальный код'),
            preserve_default=False,
        ),
    ]
