# Generated by Django 5.0.3 on 2024-03-19 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_referralcode_reference_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referralcode',
            old_name='referral_due_date',
            new_name='referral_code_due_date',
        ),
        migrations.RenameField(
            model_name='referralcode',
            old_name='referral_code',
            new_name='referral_code_title',
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='referral_code', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
