# Generated by Django 5.0.3 on 2024-03-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_referral_due_date_referralcode_referral_code_due_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='reference_code',
            new_name='referrer_code',
        ),
    ]
