# Generated by Django 5.0.3 on 2024-03-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_reference_code_customuser_referrer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='referrer_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код реферера'),
        ),
    ]
